name: Run the script

on:
   schedule: 
      - cron: '30 17 * * 0-5'

jobs:
  run-shellResource:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Run the script
        run: |
          echo Running the script .
          chmod 777  ./shell_script/AwsResource.sh
          ./shell_script/AwsResource.sh

      - name: Configure Git
        run: |
          git config --global user.name 'OmSantoshHarsule'
          git config --global user.email 'om.harsule.11@gmail.com'

      - name: Commit and push changes
        run: |
            git add ./shell_script/AWS.txt
            git commit -m "Add/update Resource.txt"
            git push
